(source "melpa" "http://melpa.milkbox.net/packages/")
(source gnu)
(source marmalade)

(depends-on "auto-complete")
(depends-on "better-defaults")
(depends-on "cask")
(depends-on "cider")
(depends-on "clojure-mode")
(depends-on "color-theme")
(depends-on "color-theme-monokai")
(depends-on "dash")
(depends-on "ensime")
(depends-on "epl")
(depends-on "f")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "pkg-info")
(depends-on "popup")
(depends-on "projectile")
(depends-on "queue")
(depends-on "s")
(depends-on "sbt-mode")
(depends-on "scala-mode2")
(depends-on "shut-up")
(depends-on "yasnippet")