(add-to-list 'load-path "~/.emacs.d/elpa/")

(load-file "~/.emacs.d/settings/1-functions.el")
(load-file "~/.emacs.d/settings/2-init-package-manager.el")
(load-file "~/.emacs.d/settings/3-init-settings.el")
(load-file "~/.emacs.d/settings/4-global-keymap.el")

(load-file "~/.emacs.d/settings/company.el")
(load-file "~/.emacs.d/settings/epa.el")
(load-file "~/.emacs.d/settings/fira-code.el")
(load-file "~/.emacs.d/settings/flycheck.el")
(load-file "~/.emacs.d/settings/git.el")
(load-file "~/.emacs.d/settings/graphviz.el")
(load-file "~/.emacs.d/settings/haskell.el")
(load-file "~/.emacs.d/settings/ido.el")
(load-file "~/.emacs.d/settings/javascript.el")
(load-file "~/.emacs.d/settings/lsp-mode.el")
(load-file "~/.emacs.d/settings/markdown.el")
(load-file "~/.emacs.d/settings/mmm.el")
(load-file "~/.emacs.d/settings/org.el")
(load-file "~/.emacs.d/settings/paredit.el")
(load-file "~/.emacs.d/settings/powerline.el")
(load-file "~/.emacs.d/settings/projectile.el")
(load-file "~/.emacs.d/settings/rainbow-delimiters.el")
(load-file "~/.emacs.d/settings/rust.el")
(load-file "~/.emacs.d/settings/scala-mode.el")
(load-file "~/.emacs.d/settings/which-key.el")
(load-file "~/.emacs.d/settings/yaml-mode.el")
(load-file "~/.emacs.d/settings/yasnippets.el")
