#!/usr/bin/env python
# -*- coding: utf-8 -*-

__author__    = "Alexandru Nedelcu"
__email__     = "alex@magnolialabs.com"
__copyright__ = "Copyright `(format-time-string "%Y")`, Magnolia Labs Inc."


from django.db import models


$0
