#!/usr/bin/env python
# -*- coding: utf-8 -*-

__author__    = "Alexandru Nedelcu"
__email__     = "contact@alexn.org"


from django.conf.urls.defaults import *
from appname import views


urlpatterns = patterns(
    '',
    # url(r'url-path/?$', views.name, name='placement'),
)
